
jobs:
  steps:
    - uses: idevqa/interval@master
    - name: Ready for Repo
      run: | 
        echo 'Ready for Hugo env'
        pwd 
        rake ready sys='ubuntu'
    - name: Publish page
      run: |
        rake 