baseURL: https://iosgua.com/interval
title: 一瓜 iOS 面试小册
relativeURLs: false
languageCode: zh-CN
theme: book

enableGitInfo: true


markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

# menu:
#   before:
#     - name: "Github"
#       url: "https://github.com/alex-shpak/hugo-book"
#       weight: 10
#     - name: "Hugo Themes"
#       url: "https://themes.gohugo.io/hugo-book/"
#       weight: 20

params:
  BookMenuBundle: /menu
  BookRepo: 'https://github.com/idevqa/interval-content'
  BookEditPath: /edit/master/

  WechatQRCode: https://raw.githubusercontent.com/Desgard/algo/img/img/_index/wechat-qrcode.png