name: Publish Page

on:
  repository_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Ready for Repo
      run: | 
        rake ready sys="ubuntu"
    - name: Publish
      run: rake 
