name: Publish Page

on:
  repository_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Ready for Repo
      run: | 
        echo 'Ready for Hugo env'
        pwd 
        rake ready sys='ubuntu'
    - name: Publish page
      run: |
        rake 